#!/bin/zsh

packpath=~/.vim/pack
name=$0

function usage {
    echo "usage: $name [-luth]"
}

function description {
    echo "$name -- manage vim packages\n  -l\tlist installed packages\n  -u\tupgrade all packages\n  -t\tgenerate help tags for all packages\n  -h\tprint this help message"
}

if [[ $# -eq 0 ]]; then
    usage
    exit 1
fi

lflag=
uflag=
tflag=

while getopts luth arg; do
    case $arg in
        l) lflag=1;;
        u) uflag=1;;
        t) tflag=1;;
        h) description; exit 0;;
        ?) usage; exit 2;;
    esac
done

[[ -a $packdir ]] && { echo "packpath=~/.vim/pack does not exist"; exit 3 }

cd "$packpath"
 
if [[ -n $lflag ]]; then
    for dir in ./*/opt/*; do
        echo "$dir"
    done
    exit 0
fi

for dir in ./*/opt/*; do
    if [[ -n $uflag ]]; then
        print -P "%F{yellow}updating $dir%f"
        git -C "$dir" pull
    fi
    if [[ -n $tflag ]]; then
        print -P "%F{yellow}generating helptags for $dir%f"
        vim -c "helptags $dir/doc | q"
    fi
done
